from tkinter import *
from tkinter import messagebox
window=Tk()
window.title("App1") 
window.geometry("500x550")
window.resizable(0,0)
f_name=Entry(window)
f_name_val=f_name.get()
l_name=Entry(window)
address=Entry(window)
e_mail=Entry(window)
Mobile_no=Entry(window)
user_id=Entry(window)
password=Entry(window,show="*")
f_name.pack()
l_name.pack()
address.pack()
e_mail.pack()
Mobile_no.pack()
user_id.pack()
password.pack()
print(f_name_val)
window.mainloop()

